-- ============================================================
-- Seed: plantilla_whatsapp
-- Idempotency: INSERT IGNORE
-- ============================================================
SET NAMES utf8mb4;
USE facturas_monrachem;
INSERT IGNORE INTO `plantilla_whatsapp` (`id_plantilla`, `activo`, `categoria`, `codigo_meta`, `contenido`, `create_date`, `estado_meta`, `fecha_aprobacion`, `idioma`, `nombre`, `parametros`, `template_id`, `update_date`, `create_by`, `update_by`) VALUES (1,_binary '','UTILITY','factura_generada','Hola {{1}}, tu factura #{{2}} por {{3}} ha sido generada.\n\n­ƒôà Fecha de vencimiento: {{4}}\n­ƒöù Ver detalles: {{5}}\n\nGracias por tu preferencia.',NULL,'APPROVED','2025-10-27 01:08:57.000000','es_CRI','factura_generada','[\"nombre_cliente\", \"numero_factura\", \"monto\", \"fecha_vencimiento\", \"url_detalle\"]',NULL,NULL,NULL,NULL);
INSERT IGNORE INTO `plantilla_whatsapp` (`id_plantilla`, `activo`, `categoria`, `codigo_meta`, `contenido`, `create_date`, `estado_meta`, `fecha_aprobacion`, `idioma`, `nombre`, `parametros`, `template_id`, `update_date`, `create_by`, `update_by`) VALUES (2,_binary '','UTILITY','recordatorio_pago','Hola {{1}},\n\n­ƒöö Recordatorio amistoso:\nTu factura #{{2}} por {{3}} vence {{4}}.\n\n­ƒÆ│ Puedes realizar el pago en:\n{{5}}\n\n┬┐Tienes alguna pregunta? Responde a este mensaje.',NULL,'APPROVED','2025-10-27 01:08:57.000000','es_CRI','recordatorio_pago','[\"nombre_cliente\", \"numero_factura\", \"monto\", \"fecha_vencimiento\", \"metodos_pago\"]',NULL,NULL,NULL,NULL);
INSERT IGNORE INTO `plantilla_whatsapp` (`id_plantilla`, `activo`, `categoria`, `codigo_meta`, `contenido`, `create_date`, `estado_meta`, `fecha_aprobacion`, `idioma`, `nombre`, `parametros`, `template_id`, `update_date`, `create_by`, `update_by`) VALUES (3,_binary '','UTILITY','pago_recibido','Ô£à ┬íPago confirmado!\n\nHola {{1}}, hemos recibido tu pago de {{2}} por la factura #{{3}}.\n\n­ƒôà Fecha de pago: {{4}}\n­ƒÆ│ M├®todo: {{5}}\n\nGracias por tu puntualidad.',NULL,'APPROVED','2025-10-27 01:08:57.000000','es_CRI','pago_recibido','[\"nombre_cliente\", \"monto\", \"numero_factura\", \"fecha_pago\", \"metodo_pago\"]',NULL,NULL,NULL,NULL);
INSERT IGNORE INTO `plantilla_whatsapp` (`id_plantilla`, `activo`, `categoria`, `codigo_meta`, `contenido`, `create_date`, `estado_meta`, `fecha_aprobacion`, `idioma`, `nombre`, `parametros`, `template_id`, `update_date`, `create_by`, `update_by`) VALUES (4,_binary '','UTILITY','factura_vencida','ÔÜá´©Å Factura vencida\n\nHola {{1}},\n\nLa factura #{{2}} por {{3}} venci├│ el {{4}}.\n\nPor favor, realiza el pago a la brevedad para evitar cargos adicionales.\n\n­ƒô× ┬┐Necesitas ayuda? Cont├íctanos respondiendo este mensaje.',NULL,'APPROVED','2025-10-27 01:08:57.000000','es_CRI','factura_vencida','[\"nombre_cliente\", \"numero_factura\", \"monto\", \"fecha_vencimiento\"]',NULL,NULL,NULL,NULL);
INSERT IGNORE INTO `plantilla_whatsapp` (`id_plantilla`, `activo`, `categoria`, `codigo_meta`, `contenido`, `create_date`, `estado_meta`, `fecha_aprobacion`, `idioma`, `nombre`, `parametros`, `template_id`, `update_date`, `create_by`, `update_by`) VALUES (5,_binary '','MARKETING','bienvenida_cliente','┬íBienvenido/a {{1}}! ­ƒæï\n\nGracias por confiar en nosotros. A partir de ahora recibir├ís notificaciones de tus facturas y pedidos por WhatsApp.\n\nÔ£¿ Beneficios:\nÔÇó Alertas de facturas\nÔÇó Recordatorios de pago\nÔÇó Atenci├│n personalizada\n\nResponde \"AYUDA\" para ver opciones disponibles.',NULL,'APPROVED','2025-10-27 01:08:57.000000','es_CRI','bienvenida_cliente','[\"nombre_cliente\"]',NULL,NULL,NULL,NULL);
