-- V5__rrhh_empleados.sql
-- Empleados table — depends on V3 (departamentos, puestos) and uses usuario.id_usuario (INT)

CREATE TABLE empleados (
    id                           BIGINT AUTO_INCREMENT PRIMARY KEY,
    cedula                       VARCHAR(20)  NOT NULL UNIQUE,
    nombre                       VARCHAR(200) NOT NULL,
    primer_apellido              VARCHAR(100) NOT NULL,
    segundo_apellido             VARCHAR(100),
    genero                       VARCHAR(10),
    estado_civil                 VARCHAR(20),
    email                        VARCHAR(100) UNIQUE,
    telefono                     VARCHAR(15),
    direccion                    TEXT,
    fecha_nacimiento             DATE,
    departamento_id              BIGINT       NOT NULL,
    puesto_id                    BIGINT       NOT NULL,
    fecha_ingreso                DATE         NOT NULL,
    fecha_salida                 DATE,
    motivo_salida                VARCHAR(500),
    estado                       VARCHAR(30)  NOT NULL DEFAULT 'ACTIVO',
    activo                       BOOLEAN      NOT NULL DEFAULT TRUE,
    numero_asegurado_ccss        VARCHAR(20)  UNIQUE,
    operadora_pensiones_rop      VARCHAR(100),
    hijos_carga_familiar         INT          NOT NULL DEFAULT 0,
    conyuge_carga_familiar       BOOLEAN      NOT NULL DEFAULT FALSE,
    porcentaje_solidarista       DECIMAL(5,4),
    monto_pension_alimentaria    DECIMAL(19,2),
    cuenta_bancaria              VARCHAR(30),
    banco                        VARCHAR(100),
    contacto_emergencia_nombre   VARCHAR(200),
    contacto_emergencia_telefono VARCHAR(15),
    contacto_emergencia_relacion VARCHAR(50),
    foto_url                     VARCHAR(500),
    usuario_id                   INT,
    created_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (departamento_id) REFERENCES departamentos(id),
    FOREIGN KEY (puesto_id)       REFERENCES puestos(id),
    FOREIGN KEY (usuario_id)      REFERENCES usuario(id_usuario),
    INDEX idx_cedula        (cedula),
    INDEX idx_activo        (activo),
    INDEX idx_departamento  (departamento_id),
    INDEX idx_fecha_ingreso (fecha_ingreso)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
